name: CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  package-jammy-amd64:
    name: Package for jammy amd64
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: "Running build"
        run: sudo ./build-package.sh x86_64
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-jammy-amd64
          path: "*.deb"

  package-noble-amd64:
    name: Package for noble amd64
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: "Running build"
        run: sudo ./build-package.sh x86_64
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-noble-amd64
          path: "*.deb"

  package-jammy-arm64:
    name: Package for jammy arm64
    runs-on: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: "Running build"
        run: sudo ./build-package.sh arm64
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-jammy-arm64
          path: "*.deb"

  package-noble-arm64:
    name: Package for noble arm64
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: "Running build"
        run: sudo ./build-package.sh arm64
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-noble-arm64
          path: "*.deb"

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ package-jammy-amd64, package-noble-amd64, package-jammy-arm64, package-noble-arm64 ]

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: artifacts-*
          merge-multiple: true

      - name: List artifacts
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/**.deb
